site_name: TNA Frontend Documentation - The National Archives
site_url: https://nationalarchives.github.io/tna-frontend-docs/
repo_url: https://github.com/nationalarchives/tna-frontend-docs
dev_addr: localhost:6007
use_directory_urls: true
nav:
  - Home:
    - index.md
  - Get started:
    - get-started/index.md
    - Using TNA Frontend:
      - get-started/using-tna-frontend/index.md
      - Compiled files: get-started/using-tna-frontend/compiled.md
      - npm: get-started/using-tna-frontend/npm.md
      - CDN: get-started/using-tna-frontend/cdn.md
    - Analytics: get-started/analytics.md
    - Cookies: get-started/cookies.md
  - Developing:
    - developing/index.md
    - Accessibility: developing/accessibility.md
    - Contributing: developing/contributing.md
    - Publishing: developing/publishing.md
  - Structure:
    - structure.md
  - History:
    - history.md
theme:
  name: material
  favicon: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.integrate
  palette:
    - primary: custom
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
